json_rpc_url: https://doublezero-mainnet-beta.rpcpool.com/db336024-e7a8-46b1-80e5-352dd77060ab
websocket_url: wss://doublezero-mainnet-beta.rpcpool.com/db336024-e7a8-46b1-80e5-352dd77060ab
program_id: ser2VaTMAcYTaauMrTSfSrxBaUDq7BLNs2xfUugTAGv
