apiVersion: 1

datasources:
  - name: doublezero-lake
    type: grafana-postgresql-datasource
    access: proxy
    url: host.docker.internal:15432
    database: dzlake
    user: grafana
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

