name: go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: make go-build
  go-lint:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: golangci/golangci-lint-action@v8
      - run: make go-lint
  go-test:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: sudo sysctl -w net.ipv4.ping_group_range="0 0"
      - run: make go-test nocontainertest
  go-container-test:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: docker/setup-buildx-action@v3
      - run: make go-container-test
  go-fuzz:
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: make go-fuzz
