name: releaser.activator

on:
  push:
    tags:
      - "activator/v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: doublezero-k8s-generic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: |
            target
            target/x86_64-unknown-linux-gnu/release
      - name: Install rust for cli
        uses: dtolnay/rust-toolchain@1.90.0
      - name: Install dependencies for rpm packaging
        run: |
          sudo apt update
          sudo apt-get install squashfs-tools rpm -y
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          args: release -f release/.goreleaser.testnet.activator.yaml --clean
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOTS_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
