name: release pipeline validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  validate_pipeline:
    runs-on: doublezero-k8s-ci
    strategy:
      matrix:
        include:
          - release: activator
            languages: ["rust"]
          - release: agent
            languages: ["go"]
          - release: client
            languages: ["go", "rust"]
          - release: controller
            languages: ["go"]
          - release: device-telemetry-agent
            languages: ["go"]
          - release: funder
            languages: ["go"]
          - release: monitor
            languages: ["go"]
          - release: qa-agent
            languages: ["go"]
          - release: s3-uploader
            languages: ["go"]
          - release: global-monitor
            languages: ["go"]
    name: release-validation-${{ matrix.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
        if: contains(matrix.languages, 'go')

      - uses: Swatinem/rust-cache@v2
        if: contains(matrix.languages, 'rust')
        with:
          cache-targets: |
            target
            target/x86_64-unknown-linux-gnu/release

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0
        if: contains(matrix.languages, 'rust')

      - name: Install dependencies for rpm packaging
        run: |
          sudo apt update
          sudo apt-get install build-essential pkg-config libssl-dev squashfs-tools rpm -y

      - name: Set env vars
        run: ./scripts/env.sh >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          args: release --snapshot -f release/.goreleaser.base.${{ matrix.release }}.yaml --clean
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_BOTS_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
