name: rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-build:
    runs-on: doublezero-k8s-generic
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: Swatinem/rust-cache@v2
      - name: Install agave solana tools
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.3.13/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: make rust-build
  rust-lint:
    runs-on: doublezero-k8s-generic
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: make rust-lint
  rust-test:
    runs-on: doublezero-k8s-generic
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: Swatinem/rust-cache@v2
      - name: Install agave solana tools
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.3.13/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: make rust-test
  rust-validator-test:
    runs-on: doublezero-k8s-generic
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - uses: Swatinem/rust-cache@v2
      - name: Install agave solana tools
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.3.13/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: make rust-validator-test
